[project]
name = "english-teacher-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "django-axes>=8.0.0",
    "python-dotenv",
    "psycopg2-binary>=2.9.11",
]
